name: Swift Format

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: swift-format-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Check Swift Formatting
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install curl
        run: |
          sudo apt-get -q update
          sudo apt-get -yq install curl

      - name: Check Swift Format
        run: |
          curl -sL \
            https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/check-swift-format.sh \
            | bash
