name: Swift Format

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: swift-format-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Check Swift Formatting
    runs-on: ubuntu-24.04

    container:
      image: swift:6.2-jammy

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Verify Swift Format
        run: swift-format --version

      - name: Run Swift Format
        run: |
          swift-format format \
            --parallel \
            --in-place \
            $(git ls-files '*.swift')

      - name: Check formatting
        run: |
          git diff --exit-code -- '*.swift'
